### ISSUE TITLE
flowClust Binary on BioC devel

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowClust#20]
@mikejiang, is there any chance of getting a flowClust binary for BioC devel? It looks like we can only install from source at the moment.

**Comment by mikejiang** [comment]
What's your error when compiling from source?

**Comment by DillonHammill** [comment]
I think it is to do with my gsl setup, it terminates on the first line. I am currently away from my computer, I will post more details tomorrow.

**Comment by DillonHammill** [comment]
@mikejiang, this the error I get:

```{r}
* installing *source* package 'flowClust' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG -I/src/include -I/i386/include    -I"C:/projects/BUILD/R-source-win32/extsoft/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -c BoxCox.c -o BoxCox.o
In file included from BoxCox.c:1:0:
flowClust.h:1:26: fatal error: gsl/gsl_math.h: No such file or directory
 #include <gsl/gsl_math.h>
                          ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-devel/etc/i386/Makeconf:208: BoxCox.o] Error 1
ERROR: compilation failed for package 'flowClust'
* removing 'C:/Users/dillo/Documents/R/win-library/4.0/flowClust'

The downloaded source packages are in
	‘C:\Users\dillo\AppData\Local\Temp\Rtmp8En0wN\downloaded_packages’
Installation path not writeable, unable to update packages: survival
Warning message:
In install.packages(...) :
  installation of package ‘flowClust’ had non-zero exit status
```

My gsl 2.6 in currently located in C:. Is this location OK?

I have intel MKL installed in Program Files (x86) as IntelSWTools. I think mkl is located in IntelSWTools>compilers_and_libraries>windows>mkl.

Is there any additional setup steps required?

It would be great if the binary was available as I suspect these setup steps will be too complicated for many. I think I have only ever been able to install the flowClust binary.

**Comment by DillonHammill** [comment]
@mikejiang, I have GnuWin32 installed in Program Files (x86) and I have added it the PATH:
![GNUWIN32 PATH](https://user-images.githubusercontent.com/28646736/76474333-6e10a500-644f-11ea-8fde-ad84d32b1760.PNG)

I also created environment variables for GSL_LIB and GSL_INC:
![GSL ENV](https://user-images.githubusercontent.com/28646736/76474356-81237500-644f-11ea-8b54-562f25c6efa2.PNG)

But still getting the same result when trying to install flowClust:
```{r}
* installing *source* package 'flowClust' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG -I/src/include -I/i386/include    -I"C:/projects/BUILD/R-source-win32/extsoft/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -c BoxCox.c -o BoxCox.o
In file included from BoxCox.c:1:0:
flowClust.h:1:26: fatal error: gsl/gsl_math.h: No such file or directory
 #include <gsl/gsl_math.h>
                          ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-devel/etc/i386/Makeconf:208: BoxCox.o] Error 1
ERROR: compilation failed for package 'flowClust'
* removing 'C:/Users/dillo/Documents/R/win-library/4.0/flowClust'
```

Any suggestions?

**Comment by DillonHammill** [comment]
I have been at it for hours, I think it is now correct based on vignette instructions but install still fails
![image](https://user-images.githubusercontent.com/28646736/76480049-b8028680-6461-11ea-933f-2f7531a86a0f.png)

**Comment by mikejiang** [comment]
Are you sure `gsl/gsl_math.h` is in your `GnuWin32/include` ?

**Comment by mikejiang** [comment]
Btw, I pushed the temporary bioc check fix for windows so that it will build the binary for you, which should appear the next day.

**Comment by DillonHammill** [comment]
@mikejiang, looks like gsl_math.h is in my GnuWin32/include:
![GnuWin32](https://user-images.githubusercontent.com/28646736/76556809-5dfbd280-64ee-11ea-915b-65f9c9f34985.PNG)

Thanks for pushing the fix, I really appreciate it!

Not sure why the gsl is still not working...

**Comment by mikejiang** [comment]
I saw `C:/projects/BUILD/R-source-win32/extsoft/include` is in your default include path, why don't you copy `gsl` folder there

**Comment by DillonHammill** [comment]
Hmm... I don't have a projects directory in C:?

**Comment by DillonHammill** [comment]
Should I try using Cygwin?

**Comment by DillonHammill** [comment]
How do I change this default path? On my main computer this is set to `C:/PROGRA~1/R/R-36~1.1/include` ?

**Comment by DillonHammill** [comment]
I managed to get a bit further on my main machine by copying `gsl` to my R include folder:

```{r}
* installing *source* package 'flowClust' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG -I/src/include -I/i386/include         -O3 -Wall  -std=gnu99 -mtune=generic -c BoxCox.c -o BoxCox.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG -I/src/include -I/i386/include         -O3 -Wall  -std=gnu99 -mtune=generic -c BoxCoxPriors.c -o BoxCoxPriors.o
BoxCoxPriors.c: In function 'BoxCoxGradientPriors':
BoxCoxPriors.c:57:16: warning: unused variable 'rowZ' [-Wunused-variable]
  rowPrecision, rowZ, rowLambda0;
                ^
BoxCoxPriors.c:33:24: warning: unused variable 'kappa0' [-Wunused-variable]
  double *nu0 = p->nu0, kappa0 = p->kappa0;
                        ^
BoxCoxPriors.c:32:7: warning: unused variable 'itersolve' [-Wunused-variable]
  int *itersolve = p->itersolve;
       ^
BoxCoxPriors.c:31:6: warning: unused variable 'iter' [-Wunused-variable]
  int iter = p->iter;
      ^
BoxCoxPriors.c:28:6: warning: unused variable 'model' [-Wunused-variable]
  int model = *p->model;
      ^
BoxCoxPriors.c:23:14: warning: unused variable 'SumZlogY' [-Wunused-variable]
  gsl_vector *SumZlogY = p->SumZlogY;
              ^
BoxCoxPriors.c:15:14: warning: unused variable 'Precision' [-Wunused-variable]
  gsl_matrix *Precision = p->Precision; // will be updated
              ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG -I/src/include -I/i386/include         -O3 -Wall  -std=gnu99 -mtune=generic -c Nu.c -o Nu.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG -I/src/include -I/i386/include         -O3 -Wall  -std=gnu99 -mtune=generic -c flowClust.c -o flowClust.o
flowClust.c: In function 'flowClust':
flowClust.c:48:2: warning: unused variable 'matrixZUY2' [-Wunused-variable]
  matrixZUY2;
  ^
flowClust.c:46:48: warning: unused variable 'subRowZUY2' [-Wunused-variable]
  rowYTransS, rowZUY, subRowZUY, rowZ, rowZUY2, subRowZUY2;
                                                ^
flowClust.c:46:39: warning: unused variable 'rowZUY2' [-Wunused-variable]
  rowYTransS, rowZUY, subRowZUY, rowZ, rowZUY2, subRowZUY2;
                                       ^
flowClust.c: In function 'ECMUpdateSigmaG2':
flowClust.c:1111:6: warning: unused variable 'i' [-Wunused-variable]
  int i=0;
      ^
flowClust.c: In function 'flowClust':
flowClust.c:383:13: warning: 's' may be used uninitialized in this function [-Wmaybe-uninitialized]
        x_hi = gsl_root_fsolver_x_upper(s);
             ^
flowClust.c:713:12: warning: 's3' may be used uninitialized in this function [-Wmaybe-uninitialized]
      nu_hi = gsl_min_fminimizer_x_upper(s3);
            ^
flowClust.c:675:14: warning: 's2' may be used uninitialized in this function [-Wmaybe-uninitialized]
        nu_hi = gsl_root_fsolver_x_upper(s2);
              ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG -I/src/include -I/i386/include         -O3 -Wall  -std=gnu99 -mtune=generic -c flowClustGaussian.c -o flowClustGaussian.o
flowClustGaussian.c: In function 'flowClustGaussian':
flowClustGaussian.c:242:13: warning: 's' may be used uninitialized in this function [-Wmaybe-uninitialized]
        x_hi = gsl_root_fsolver_x_upper(s);
             ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG -I/src/include -I/i386/include         -O3 -Wall  -std=gnu99 -mtune=generic -c ranMVNT.c -o ranMVNT.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o flowClust.dll tmp.def BoxCox.o BoxCoxPriors.o Nu.o flowClust.o flowClustGaussian.o ranMVNT.o -L/i386/lib -lgsl -lgslcblas -lm -LC:/PROGRA~1/R/R-36~1.1/bin/i386 -lR
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgsl
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgslcblas
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'flowClust'
* removing 'C:/Program Files/R/R-3.6.1/library/flowClust'
* restoring previous 'C:/Program Files/R/R-3.6.1/library/flowClust'
Error: Failed to install 'flowClust' from GitHub:
  (converted from warning) installation of package ‘C:/Users/LOCALU~1.JCS/AppData/Local/Temp/RtmpcLc6Hh/file21e0728657ee/flowClust_3.25.1.tar.gz’ had non-zero exit status
```

**Comment by DillonHammill** [comment]
Why is not using the paths specified in the environment variables?

**Comment by mikejiang** [comment]
The current installation instruction for windows in `README` is out of date. I will need to update it (probably tomorrow)

**Comment by DillonHammill** [comment]
OK, thanks @mikejiang! I will try again once these instructions have been updated.

**Comment by mikejiang** [comment]
Just so you know the bioc binary is available now.

**Comment by DillonHammill** [comment]
Excellent! Thanks for letting me know.
